brew "fish"
brew "neovim", args: ["HEAD"]
brew "tmux"
brew "ripgrep"
brew "bat"
brew "fd"
brew "fzf"
brew "git-delta"
brew "mise"
brew "starship"
brew "zoxide"
brew "difftastic"
brew "colima"
brew "docker"
brew "gh"
brew "lazydocker"
brew "lazygit"
brew "rustup"
brew "tree-sitter-cli"
brew "xdg-ninja"

cask "font-iosevka"
cask "font-jetbrains-mono"
cask "ghostty"
cask "google-chrome"
cask "raycast"
cask "spotify"
