# Portable CLI tools live in the `tools` package in flake.nix. Homebrew is
# kept for macOS integration and applications distributed as casks.
brew "pam-reattach"
cask "orbstack"
cask "font-iosevka"
cask "font-jetbrains-mono"
cask "font-symbols-only-nerd-font"
cask "claude"
cask "claude-code@latest"
cask "codex"
cask "1password"
cask "1password-cli"
cask "ghostty"
cask "google-chrome"
cask "raycast"
cask "spotify"
cask "protonvpn"
cask "winbox"
