extra-substituters = https://nix-community.cachix.org
extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

extra-substituters = https://sindrip.cachix.org
extra-trusted-public-keys = sindrip.cachix.org-1:tni1LcPdMGxgmv3ZseA3ULu3oMwR5iz1/0p9ibhBPHE=
