-- vim.g.mapleader = " "
-- vim.g.maplocalleader = "\\"
-- -- Interesting thing to look at
-- -- vim.o.virtualedit = "block"
-- -- Search options
-- vim.o.ignorecase = true
-- vim.o.smartcase = true
-- vim.o.inccommand = "split"
-- -- Indentation
-- vim.o.shiftwidth = 4
-- vim.o.tabstop = 4
-- vim.o.expandtab = true
-- vim.o.undofile = true -- Can't live without this
-- vim.o.number = true
-- vim.o.relativenumber = true
-- vim.o.signcolumn = "yes"
-- vim.o.cursorline = true
-- vim.o.list = true
-- vim.opt.listchars = { tab = "→ ", nbsp = "␣", trail = "·", -- space = "·", extends = "⟩", precedes = "⟨", }
-- -- vim.o.wrap = false
-- -- Splits
-- -- vim.o.splitkeep = 'screen'
-- vim.o.splitbelow = true
-- vim.o.splitright = true
-- -- Status line
-- vim.o.laststatus = 3
-- vim.o.cmdheight = 1
-- vim.o.scrolloff = 8
-- vim.o.sidescrolloff = 5
-- vim.opt.completeopt = { "menu", "menuone", "noselect" }
-- vim.o.winborder = "rounded"
-- -- Folds
-- -- vim.o.foldcolumn = "1"
-- vim.o.foldlevel = 99
-- vim.o.foldnestmax = 3
-- vim.opt.fillchars:append({ fold = " " })
-- vim.o.foldtext = ""

----------- Yes ---------------
-- 'breakindent'	  'bri'     wrapped line repeats indent
-- 'breakindentopt'  'briopt'  settings for 'breakindent'
--== breakindentopt=shift:2

-- 'linebreak'	  'lbr'     wrap long lines at a blank

-- 'colorcolumn'	  'cc'	    columns to highlight
--== Figure this one out


----------- Maybe ---------------
-- 'autowrite'	  'aw'	    automatically write file if changed

-- 'confirm'	  'cf'	    ask what to do about unsaved/read-only files

-- 'cursorlineopt'	  'culopt'  settings for 'cursorline'
--== with wrap this is interesting
--== cursorlineopt=screenline,number
---------------------------------
-- Take a look at
-- 12. Special kinds of buffers			*special-buffers*
---------------------------------

-- 'debug'			    set to "msg" to see all error messages
-- 'define'	  'def'     pattern to be used to find a macro definition
-- 'delcombine'	  'deco'    delete combining characters on their own
-- 'dictionary'	  'dict'    list of file names used for keyword completion
-- 'diff'			    use diff mode for the current window
-- 'diffanchors'	  'dia'     list of {address} to force anchoring of a diff
-- 'diffexpr'	  'dex'     expression used to obtain a diff file 
-- 'diffopt'	  'dip'     options for using diff mode
-- 'digraph'	  'dg'	    enable the entering of digraphs in Insert mode
-- 'directory'	  'dir'     list of directory names for the swap file
-- 'display'	  'dy'	    list of flags for how to display text
-- 'eadirection'	  'ead'     in which direction 'equalalways' works
-- 'encoding'	  'enc'     encoding used internally
-- 'endoffile'	  'eof'     write CTRL-Z at end of the file
-- 'endofline'	  'eol'     write <EOL> for last line in file
-- 'equalalways'	  'ea'	    windows are automatically made the same size
-- 'equalprg'	  'ep'	    external program to use for "=" command
-- 'errorbells'	  'eb'	    ring the bell for error messages
-- 'errorfile'	  'ef'	    name of the errorfile for the QuickFix mode
-- 'errorformat'	  'efm'     description of the lines in the error file
-- 'eventignore'	  'ei'	    autocommand events that are ignored
-- 'eventignorewin'  'eiw'     autocommand events that are ignored in a window
-- 'expandtab'	  'et'	    use spaces when <Tab> is inserted
-- 'exrc'		  'ex'	    read init files in the current directory
-- 'fileencoding'	  'fenc'    file encoding for multibyte text
-- 'fileencodings'   'fencs'   automatically detected character encodings
-- 'fileformat'	  'ff'	    file format used for file I/O
-- 'fileformats'	  'ffs'     automatically detected values for 'fileformat'
-- 'fileignorecase'  'fic'     ignore case when using file names
-- 'filetype'	  'ft'	    type of file, used for autocommands
-- 'fillchars'	  'fcs'     characters to use for displaying special items
-- 'findfunc'	  'ffu'     function to be called for the |:find| command
-- 'fixendofline'	  'fixeol'  make sure last line in file has <EOL>
-- 'foldclose'	  'fcl'     close a fold when the cursor leaves it
-- 'foldcolumn'	  'fdc'     width of the column used to indicate folds
-- 'foldenable'	  'fen'     set to display all folds open
-- 'foldexpr'	  'fde'     expression used when 'foldmethod' is "expr"
-- 'foldignore'	  'fdi'     ignore lines when 'foldmethod' is "indent"
-- 'foldlevel'	  'fdl'     close folds with a level higher than this
-- 'foldlevelstart'  'fdls'    'foldlevel' when starting to edit a file
-- 'foldmarker'	  'fmr'     markers used when 'foldmethod' is "marker"
-- 'foldmethod'	  'fdm'     folding type
-- 'foldminlines'	  'fml'     minimum number of lines for a fold to be closed
-- 'foldnestmax'	  'fdn'     maximum fold depth
-- 'foldopen'	  'fdo'     for which commands a fold will be opened
-- 'foldtext'	  'fdt'     expression used to display for a closed fold
-- 'formatexpr'	  'fex'     expression used with "gq" command
-- 'formatlistpat'   'flp'     pattern used to recognize a list header
-- 'formatoptions'   'fo'	    how automatic formatting is to be done
-- 'formatprg'	  'fp'	    name of external program used with "gq" command
-- 'fsync'		  'fs'	    whether to invoke fsync() after file write
-- 'grepformat'	  'gfm'     format of 'grepprg' output
-- 'grepprg'	  'gp'	    program to use for ":grep"
-- 'guicursor'	  'gcr'     GUI: settings for cursor shape and blinking
-- 'guifont'	  'gfn'     GUI: Name(s) of font(s) to be used
-- 'guifontwide'	  'gfw'     list of font names for double-wide characters
-- 'guioptions'	  'go'	    GUI: Which components and options are used
-- 'guitablabel'	  'gtl'     GUI: custom label for a tab page
-- 'guitabtooltip'   'gtt'     GUI: custom tooltip for a tab page
-- 'helpfile'	  'hf'	    full path name of the main help file
-- 'helpheight'	  'hh'	    minimum height of a new help window
-- 'helplang'	  'hlg'     preferred help languages
-- 'hidden'	  'hid'     don't unload buffer when it is |abandon|ed
-- 'history'	  'hi'	    number of command-lines that are remembered
-- 'hlsearch'	  'hls'     highlight matches with last search pattern
-- 'icon'			    let Vim set the text of the window icon
-- 'iconstring'		    string to use for the Vim icon text
-- 'ignorecase'	  'ic'	    ignore case in search patterns
-- 'imcmdline'	  'imc'     use IM when starting to edit a command line
-- 'imdisable'	  'imd'     do not use the IM in any mode
-- 'iminsert'	  'imi'     use :lmap or IM in Insert mode
-- 'imsearch'	  'ims'     use :lmap or IM when typing a search pattern
-- 'include'	  'inc'     pattern to be used to find an include file
-- 'includeexpr'	  'inex'    expression used to process an include line
-- 'incsearch'	  'is'	    highlight match while typing search pattern
-- 'indentexpr'	  'inde'    expression used to obtain the indent of a line
-- 'indentkeys'	  'indk'    keys that trigger indenting with 'indentexpr'
-- 'infercase'	  'inf'     adjust case of match for keyword completion
-- 'isfname'	  'isf'     characters included in file names and pathnames
-- 'isident'	  'isi'     characters included in identifiers
-- 'iskeyword'	  'isk'     characters included in keywords
-- 'isprint'	  'isp'     printable characters
-- 'joinspaces'	  'js'	    two spaces after a period with a join command
-- 'jumpoptions'	  'jop'     specifies how jumping is done
-- 'keymap'	  'kmp'     name of a keyboard mapping
-- 'keymodel'	  'km'	    enable starting/stopping selection with keys
-- 'keywordprg'	  'kp'	    program to use for the "K" command
-- 'langmap'	  'lmap'    alphabetic characters for other language mode
-- 'langmenu'	  'lm'	    language to be used for the menus
-- 'langremap'	  'lrm'	    do apply 'langmap' to mapped characters
-- 'laststatus'	  'ls'	    tells when last window has status lines
-- 'lazyredraw'	  'lz'	    don't redraw while executing macros
-- 'lhistory'	  'lhi'	    maximum number of location lists in history
-- 'lines'			    number of lines in the display
-- 'linespace'	  'lsp'     number of pixel lines to use between characters
-- 'lisp'			    automatic indenting for Lisp
-- 'lispoptions'	  'lop'     changes how Lisp indenting is done
-- 'lispwords'	  'lw'	    words that change how lisp indenting works
-- 'list'			    show <Tab> and <EOL>
-- 'listchars'	  'lcs'     characters for displaying in list mode
-- 'loadplugins'	  'lpl'     load plugin scripts when starting up
-- 'makeef'	  'mef'     name of the errorfile for ":make"
-- 'makeencoding'	  'menc'    encoding of external make/grep commands
-- 'makeprg'	  'mp'	    program to use for the ":make" command
-- 'matchpairs'	  'mps'     pairs of characters that "%" can match
-- 'matchtime'	  'mat'     tenths of a second to show matching paren
-- 'maxcombine'	  'mco'     maximum nr of combining characters displayed
-- 'maxfuncdepth'	  'mfd'     maximum recursive depth for user functions
-- 'maxmapdepth'	  'mmd'     maximum recursive depth for mapping
-- 'maxmempattern'   'mmp'     maximum memory (in Kbyte) used for pattern search
-- 'menuitems'	  'mis'     maximum number of items in a menu
-- 'mkspellmem'	  'msm'     memory used before |:mkspell| compresses the tree
-- 'modeline'	  'ml'	    recognize modelines at start or end of file
-- 'modelineexpr'	  'mle'	    allow setting expression options from a modeline
-- 'modelines'	  'mls'     number of lines checked for modelines
-- 'modifiable'	  'ma'	    changes to the text are not possible
-- 'modified'	  'mod'     buffer has been modified
-- 'more'			    pause listings when the whole screen is filled
-- 'mouse'			    enable the use of mouse clicks
-- 'mousefocus'	  'mousef'  keyboard focus follows the mouse
-- 'mousehide'	  'mh'	    hide mouse pointer while typing
-- 'mousemodel'	  'mousem'  changes meaning of mouse buttons
-- 'mousemoveevent'  'mousemev'  report mouse moves with <MouseMove>
-- 'mousescroll'		    amount to scroll by when scrolling with a mouse
-- 'mouseshape'	  'mouses'  shape of the mouse pointer in different modes
-- 'mousetime'	  'mouset'  max time between mouse double-click
-- 'nrformats'	  'nf'	    number formats recognized for CTRL-A command
-- 'number'	  'nu'	    print the line number in front of each line
-- 'numberwidth'	  'nuw'     number of columns used for the line number
-- 'omnifunc'	  'ofu'     function for filetype-specific completion
-- 'opendevice'	  'odev'    allow reading/writing devices on MS-Windows
-- 'operatorfunc'	  'opfunc'  function to be called for |g@| operator
-- 'packpath'	  'pp'      list of directories used for packages
-- 'paragraphs'	  'para'    nroff macros that separate paragraphs
-- 'patchexpr'	  'pex'     expression used to patch a file
-- 'patchmode'	  'pm'	    keep the oldest version of a file
-- 'path'		  'pa'	    list of directories searched with "gf" et.al.
-- 'preserveindent'  'pi'	    preserve the indent structure when reindenting
-- 'previewheight'   'pvh'     height of the preview window
-- 'previewwindow'   'pvw'     identifies the preview window
-- 'pumheight'	  'ph'	    maximum number of items to show in the popup menu
-- 'pumwidth'	  'pw'	    minimum width of the popup menu
-- 'pyxversion'	  'pyx'	    Python version used for pyx* commands
-- 'quoteescape'	  'qe'	    escape characters used in a string
-- 'readonly'	  'ro'	    disallow writing the buffer
-- 'redrawtime'	  'rdt'     timeout for 'hlsearch' and |:match| highlighting
-- 'regexpengine'	  're'	    default regexp engine to use
-- 'relativenumber'  'rnu'	    show relative line number in front of each line
-- 'report'		    threshold for reporting nr. of lines changed
-- 'revins'	  'ri'	    inserting characters will work backwards
-- 'rightleft'	  'rl'	    window is right-to-left oriented
-- 'rightleftcmd'	  'rlc'     commands for which editing works right-to-left
-- 'ruler'		  'ru'	    show cursor line and column in the status line
-- 'rulerformat'	  'ruf'     custom format for the ruler
-- 'runtimepath'	  'rtp'     list of directories used for runtime files
-- 'scroll'	  'scr'     lines to scroll with CTRL-U and CTRL-D
-- 'scrollbind'	  'scb'     scroll in window as other windows scroll
-- 'scrolljump'	  'sj'	    minimum number of lines to scroll
-- 'scrolloff'	  'so'	    minimum nr. of lines above and below cursor
-- 'scrollopt'	  'sbo'     how 'scrollbind' should behave
-- 'sections'	  'sect'    nroff macros that separate sections
-- 'secure'		    secure mode for reading .vimrc in current dir
-- 'selection'	  'sel'     what type of selection to use
-- 'selectmode'	  'slm'     when to use Select mode instead of Visual mode
-- 'sessionoptions'  'ssop'    options for |:mksession|
-- 'shada'		  'sd'	    use |shada| file upon startup and exiting
-- 'shell'		  'sh'	    name of shell to use for external commands
-- 'shellcmdflag'	  'shcf'    flag to shell to execute one command
-- 'shellpipe'	  'sp'	    string to put output of ":make" in error file
-- 'shellquote'	  'shq'     quote character(s) for around shell command
-- 'shellredir'	  'srr'     string to put output of filter in a temp file
-- 'shellslash'	  'ssl'     use forward slash for shell file names
-- 'shelltemp'	  'stmp'    whether to use a temp file for shell commands
-- 'shellxescape'	  'sxe'     characters to escape when 'shellxquote' is (
-- 'shellxquote'	  'sxq'     like 'shellquote', but include redirection
-- 'shiftround'	  'sr'	    round indent to multiple of shiftwidth
-- 'shiftwidth'	  'sw'	    number of spaces to use for (auto)indent step
-- 'shortmess'	  'shm'     list of flags, reduce length of messages
-- 'showbreak'	  'sbr'     string to use at the start of wrapped lines
-- 'showcmd'	  'sc'	    show (partial) command somewhere
-- 'showcmdloc'	  'sloc'    where to show (partial) command
-- 'showfulltag'	  'sft'     show full tag pattern when completing tag
-- 'showmatch'	  'sm'	    briefly jump to matching bracket if insert one
-- 'showmode'	  'smd'     message on status line to show current mode
-- 'showtabline'	  'stal'    tells when the tab pages line is displayed
-- 'sidescroll'	  'ss'	    minimum number of columns to scroll horizontal
-- 'sidescrolloff'   'siso'    min. nr. of columns to left and right of cursor
-- 'signcolumn'	  'scl'	    when and how to display the sign column
-- 'smartcase'	  'scs'     no ignore case when pattern has uppercase
-- 'smartindent'	  'si'	    smart autoindenting for C programs
-- 'smarttab'	  'sta'     <Tab> in leading whitespace indents by 'shiftwidth'
-- 'smoothscroll'	  'sms'     scroll by screen lines when 'wrap' is set
-- 'softtabstop'	  'sts'     number of columns between two soft tab stops
-- 'spell'			    enable spell checking
-- 'spellcapcheck'   'spc'     pattern to locate end of a sentence
-- 'spellfile'	  'spf'     files where |zg| and |zw| store words
-- 'spelllang'	  'spl'     language(s) to do spell checking for
-- 'spelloptions'	  'spo'     options for spell checking
-- 'spellsuggest'	  'sps'     method(s) used to suggest spelling corrections
-- 'splitbelow'	  'sb'	    new window from split is below the current one
-- 'splitkeep'	  'spk'     determines scroll behavior for split windows
-- 'splitright'	  'spr'     new window is put right of the current one
-- 'startofline'	  'sol'     commands move cursor to first non-blank in line
-- 'statuscolumn'	  'stc'	    custom format for the status column
-- 'statusline'	  'stl'     custom format for the status line
-- 'suffixes'	  'su'	    suffixes that are ignored with multiple match
-- 'suffixesadd'	  'sua'     suffixes added when searching for a file
-- 'swapfile'	  'swf'     whether to use a swapfile for a buffer
-- 'switchbuf'	  'swb'     sets behavior when switching to another buffer
-- 'synmaxcol'	  'smc'     maximum column to find syntax items
-- 'syntax'	  'syn'     syntax to be loaded for current buffer
-- 'tabclose'	  'tcl'     which tab page to focus when closing a tab
-- 'tabline'	  'tal'     custom format for the console tab pages line
-- 'tabpagemax'	  'tpm'     maximum number of tab pages for |-p| and "tab all"
-- 'tabstop'	  'ts'	    number of columns between two tab stops
-- 'tagbsearch'	  'tbs'     use binary searching in tags files
-- 'tagcase'	  'tc'      how to handle case when searching in tags files
-- 'tagfunc'	  'tfu'	    function to get list of tag matches
-- 'taglength'	  'tl'	    number of significant characters for a tag
-- 'tagrelative'	  'tr'	    file names in tag file are relative
-- 'tags'		  'tag'     list of file names used by the tag command
-- 'tagstack'	  'tgst'    push tags onto the tag stack
-- 'term'			    name of the terminal
-- 'termbidi'	  'tbidi'   terminal takes care of bi-directionality
-- 'termguicolors'	  'tgc'     enable 24-bit RGB color in the TUI
-- 'textwidth'	  'tw'	    maximum width of text that is being inserted
-- 'thesaurus'	  'tsr'     list of thesaurus files for keyword completion
-- 'thesaurusfunc'	  'tsrfu'   function to be used for thesaurus completion
-- 'tildeop'	  'top'     tilde command "~" behaves like an operator
-- 'timeout'	  'to'	    time out on mappings and key codes
-- 'timeoutlen'	  'tm'	    time out time in milliseconds
-- 'title'			    let Vim set the title of the window
-- 'titlelen'		    percentage of 'columns' used for window title
-- 'titleold'		    old title, restored when exiting
-- 'titlestring'		    string to use for the Vim window title
-- 'ttimeout'		    time out on mappings
-- 'ttimeoutlen'	  'ttm'     time out time for key codes in milliseconds
-- 'ttytype'	  'tty'     alias for 'term'
-- 'undodir'	  'udir'    where to store undo files
-- 'undofile'	  'udf'	    save undo information in a file
-- 'undolevels'	  'ul'	    maximum number of changes that can be undone
-- 'undoreload'	  'ur'	    max nr of lines to save for undo on a buffer reload
-- 'updatecount'	  'uc'	    after this many characters flush swap file
-- 'updatetime'	  'ut'	    after this many milliseconds flush swap file
-- 'varsofttabstop'  'vsts'    a list of number of columns between soft tab stops
-- 'vartabstop'	  'vts'	    a list of number of columns between tab stops
-- 'verbose'	  'vbs'     give informative messages
-- 'verbosefile'	  'vfile'   file to write messages in
-- 'viewdir'	  'vdir'    directory where to store files with :mkview
-- 'viewoptions'	  'vop'     specifies what to save for :mkview
-- 'virtualedit'	  've'	    when to use virtual editing
-- 'visualbell'	  'vb'	    use visual bell instead of beeping
-- 'warn'			    warn for shell command when buffer was changed
-- 'whichwrap'	  'ww'	    allow specified keys to cross line boundaries
-- 'wildchar'	  'wc'	    command-line character for wildcard expansion
-- 'wildcharm'	  'wcm'     like 'wildchar' but also works when mapped
-- 'wildignore'	  'wig'     files matching these patterns are not completed
-- 'wildignorecase'  'wic'     ignore case when completing file names
-- 'wildmenu'	  'wmnu'    use menu for command line completion
-- 'wildmode'	  'wim'     mode for 'wildchar' command-line expansion
-- 'wildoptions'	  'wop'     specifies how command line completion is done
-- 'winaltkeys'	  'wak'     when the windows system handles ALT keys
-- 'window'	  'wi'	    nr of lines to scroll for CTRL-F and CTRL-B
-- 'winfixbuf'	  'wfb'     keep window focused on a single buffer
-- 'winfixheight'	  'wfh'     keep window height when opening/closing windows
-- 'winfixwidth'	  'wfw'     keep window width when opening/closing windows
-- 'winheight'	  'wh'	    minimum number of lines for the current window
-- 'winhighlight'	  'winhl'   window-local highlighting
-- 'winminheight'	  'wmh'     minimum number of lines for any window
-- 'winminwidth'	  'wmw'     minimal number of columns for any window
-- 'winwidth'	  'wiw'     minimal number of columns for current window
-- 'wrap'			    long lines wrap and continue on the next line
-- 'wrapmargin'	  'wm'	    chars from the right where wrapping starts
-- 'wrapscan'	  'ws'	    searches wrap around the end of the file
-- 'write'			    writing to a file is allowed
-- 'writeany'	  'wa'	    write to file with no need for "!" override
-- 'writebackup'	  'wb'	    make a backup before overwriting a file
-- 'writedelay'	  'wd'	    delay this many msec for each char (for debug)
