set-option -g prefix C-Space
set-option -sg escape-time 0
set-option -g focus-events on
set-option -g mouse on

set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
# set-option -g mode-keys vi

bind-key x kill-pane
bind-key C-r source-file "~/.config/tmux/tmux.conf" \; display-message "tmux.conf reloaded"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'sindrip/tmux-nvim-navigator'

if "test ! -d $TMUX_PLUGIN_MANAGER_PATH/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $TMUX_PLUGIN_MANAGER_PATH/tpm'"

run '$TMUX_PLUGIN_MANAGER_PATH/tpm/tpm'
