# set-option -g prefix C-SPACE
set-option -g prefix C-b
set-option -g focus-events on
set-option -g base-index 1
set-option -g renumber-windows on
set-option -g mode-keys vi

set-option -g status-position top
set-option -g status-justify absolute-centre
set-option -g status-style "bg=default,fg=#a5adce"
set-option -g status-right ""
set-option -g status-left "#S"
set-option -g window-status-format "#[fg=#626880] #I #W "
set-option -g window-status-current-format "#[fg=#8caaee] #I #W "

bind-key r source-file "~/.config/tmux/tmux.conf"
bind-key e new-window -n "yazi" yazi
bind-key g new-window -n "lazygit" lazygit
