[settings]
idiomatic_version_file_enable_tools = ["node", "rust"]
minimum_release_age = "0s"

[tools]
"github:h4ckf0r0day/obscura" = "latest"
"npm:corepack" = "latest"
"npm:typescript-language-server" = "latest"
biome = "latest"
bun = "latest"
go = "latest"
node = "latest"
rust = "latest"
