[settings]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age = "0s"

[tools]
# Language runtimes
bun = "1.3.14"
go = "1.27rc3"
node = "26.7.0"

# Ecosystem tools
"github:h4ckf0r0day/obscura" = "0.2.0"
"npm:corepack" = "0.35.0"
