name: Neovim nightly

on:
  push:
    branches: [main]
    paths: [flake.nix, flake.lock]
  pull_request:
    paths: [flake.nix, flake.lock]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: sindrip
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#neovim -L
